spring:
  datasource:
    url: jdbc:mysql://47.104.243.201:3306/girls?characterEncoding=utf-8
    password: admin123
    driver-class-name: com.mysql.jdbc.Driver
    username: root
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 80

